<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Test Types
    |--------------------------------------------------------------------------
    |
    | Define which test types should be generated by default when using
    | the make:tdd command without specific options.
    |
    */
    'default_types' => [
        'model' => true,
        'controller' => true,
        'migration' => true,
        'routes' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Test Namespaces
    |--------------------------------------------------------------------------
    |
    | Define the namespaces for different types of tests.
    |
    */
    'namespaces' => [
        'unit' => 'Tests\\Unit',
        'feature' => 'Tests\\Feature',
        'integration' => 'Tests\\Integration',
    ],

    /*
    |--------------------------------------------------------------------------
    | Stub Customization
    |--------------------------------------------------------------------------
    |
    | Customize the stub files used for generating tests. You can publish
    | the stubs and modify them to match your project's coding standards.
    |
    */
    'stubs' => [
        'model' => 'model.test.stub',
        'controller' => 'controller.test.stub',
        'migration' => 'migration.test.stub',
        'route' => 'route.test.stub',
    ],

    /*
    |--------------------------------------------------------------------------
    | Test Data Generation
    |--------------------------------------------------------------------------
    |
    | Configure how test data should be generated for different field types.
    |
    */
    'test_data' => [
        'string_fields' => ['name', 'title', 'description', 'content'],
        'email_fields' => ['email', 'email_address'],
        'boolean_fields' => ['active', 'published', 'enabled', 'status'],
        'numeric_fields' => ['price', 'amount', 'quantity', 'count'],
        'date_fields' => ['created_at', 'updated_at', 'published_at'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Requirements
    |--------------------------------------------------------------------------
    |
    | Define which routes/actions require authentication in generated tests.
    |
    */
    'auth_required' => [
        'store' => true,
        'update' => true,
        'destroy' => true,
        'index' => false,
        'show' => false,
    ],
];